travis:
  secure:
    BINSTAR_TOKEN: zvVs83KHFMHQ/qEt0QktIsBDnAFZLc9PB+MeDPRWiWZ1ATVjA5ZjQTRlGe2nzvHVQaYmtASDTZ2gvqzDZX+zB7KbXb45oNULM96QSaZnb9D4pzbI4ZwlEst7sP0Lmw9216XaYTf4YfkVduD7lRDeVMFlf9x3PE5mWTa5xSkAmnPgR1FxWKZ+Ver0kU3uFbg8LDvLIj8h9MEJitVJ6HPKLK2Yq3uXBB5bdGLfW46dRXVZ0IKgtViJSaZP64R9v+0GSa8OLwdSCv915YMOFCugYxG6jbJ4ttnPfwQW91VI9mXAygyYJDRpQm0nZgqg9pwsx9LKu4Ur8+fRWNxoEdctPwexsG786dYrKLQoPqLShKaLCCdOzCtraQTRTc5XzuZvpsoXquBT0wGTdjus/JnyK/qmDW+nqdJ0n6RI+dT20B7zygW+K4yCR4LEFD2MFaeJYWGezATgwjLuwuEHbsEzYLYHEhVjQ/Mp3XIruRyEU7YMHtdOAOoEjMJFjQ83Ss/YP+eZy7/2v1/TUegkDIYb+8k3RdO00WWLLiTTC+DGipvOgKoBmugEw6TyGck0bgQoZ5ZgQZgJJkuaQofhCMKT/elNUbH+qKdgQtAXmbsTBA7yg4ux73TdTEc5Sm7WuRoCnywGvaWjXgP+bzs9n3h1qgiAJv/uEgtrMzCXhsvmCvQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
